### ISSUE TITLE
My two cents

### ISSUE THREAD

**Issue by edosedgar** [alloky/architect_akos#2]
1) The first annoyance I noticed is a reverse order of coefficients, for what reason?
Kinda non-conformism?
2) "there are 1 roots"
ok....
3) No '\n' after last line printed
4) Just typed "2 3 4" and you program backtraced like Linux TCP/IP stack in its first version (seems like not all possible cases are handled properly)
Enough for now, wait for fix

**Comment by alloky** [comment]
Всё из списка пофикшено
